### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MrCyjaneK** [MrCyjaneK/p3pch4t#1]
### Current project roadmap

 - [x] Initial android release
 - [ ] Support for various platforms
     - [x] Android
     - [ ] Linux
     - [ ] Windows
     - [ ] MacOS
     - [ ] ?iOS
 - [ ] #2
 - [ ] Serverless groups
 - [ ] Nice UI
 - [ ] Message reactions
 - [ ] Stickers / Gifs (grouped attachments)
 - [ ] Shared directories
 - [ ]  Client/Bot library
     - [ ] Dart
     - [ ] Golang
 - [x] Backup/Restore

That's it from the 'roadmap' there are also other things that I plan to do, such as:
 - Groups with channels (think slack/discord)
